version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_v3
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka_v3
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost